### ISSUE TITLE
File contains no section headers ? how deal with it?

### ISSUE THREAD

**Issue by inevity** [ceph/s3-tests#121]
ERROR: test suite for 
module 's3tests.functional' from '/home/deploy/s3-tests/s3tests/functional/__init__.pyc'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deploy/s3-tests/virtualenv/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/deploy/s3-tests/virtualenv/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/deploy/s3-tests/virtualenv/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/deploy/s3-tests/virtualenv/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/deploy/s3-tests/s3tests/functional/__init__.py", line 266, in setup
    cfg.readfp(f)
  File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: config.yaml.SAMPLE, line: 1
'fixtures:\n'

**Comment by inevity** [comment]
@yehudasa

**Comment by inevity** [comment]
use config.yaml.SAMPLE  lead this error.
but use the [] pass.
