### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by kaifong** [ceph/s3-tests#198]
E..................................
======================================================================
ERROR: test suite for <module 's3tests.functional' from '/home/fongy/Desktop/Working/Ceph/s3-tests-master/s3tests/functional/__init__.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fongy/Desktop/Working/Ceph/s3-tests-master/virtualenv/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/fongy/Desktop/Working/Ceph/s3-tests-master/virtualenv/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/fongy/Desktop/Working/Ceph/s3-tests-master/virtualenv/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/fongy/Desktop/Working/Ceph/s3-tests-master/virtualenv/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/fongy/Desktop/Working/Ceph/s3-tests-master/s3tests/functional/__init__.py", line 266, in setup
    cfg.readfp(f)
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: aws.conf, line: 1
'fixtures:\n'

----------------------------------------------------------------------
Ran 34 tests in 1.202s

FAILED (errors=1)

I realise that this issue had been covered here (and closed)
 
https://github.com/ceph/s3-tests/issues/121

but I don't understand the answer :(

If someone could elaborate I'd be most grateful :)

regards

kai

**Comment by yehudasa** [comment]
@kaifong note config example in `README.rst`. I think that sample applies for one of the other internal tools here.

**Comment by kaifong** [comment]
Well blow me down, I'm sure I tried that already! So I should cut and paste the sample in README.rst and replace the credentials. Thanks :)
