### ISSUE TITLE
Problem to install with Python 3.7

### ISSUE THREAD

**Issue by Issen007** [ceph/s3-tests#270]
Hi,
Has anyone try this with a newer version of Python?
I have try to install it with both Python 2.7 and Python 3.7 but both ending up with same issue.

```
(s3-tests) [chrisp@issen-lnx s3-tests]$ S3TEST_CONF=your.conf ./virtualenv/bin/nosetests
EEEEEE
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'httplib')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chrisp/github/s3-tests/s3tests/functional/__init__.py", line 11, in <module>
    from httplib import HTTPConnection, HTTPSConnection
ModuleNotFoundError: No module named 'httplib'

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (headers.py, line 341))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chrisp/github/s3-tests/s3tests/fuzz/test/test_fuzzer.py", line 21, in <module>
    from ..headers import *
  File "/home/chrisp/github/s3-tests/s3tests/fuzz/headers.py", line 341
    except BotoServerError, e:
                          ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (Missing parentheses in call to 'print'. Did you mean print('original  hash: ', self.original_hash)? (realistic.py, line 50))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chrisp/github/s3-tests/s3tests/tests/test_realistic.py", line 1, in <module>
    from s3tests import realistic
  File "/home/chrisp/github/s3-tests/s3tests/realistic.py", line 50
    print 'original  hash: ', self.original_hash
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('original  hash: ', self.original_hash)?

======================================================================
ERROR: test suite for <module 's3tests_boto3.functional' from '/home/chrisp/github/s3-tests/s3tests_boto3/functional/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/chrisp/github/s3-tests/s3tests_boto3/functional/__init__.py", line 131, in setup
    cfg = ConfigParser.RawConfigParser()
AttributeError: type object 'ConfigParser' has no attribute 'RawConfigParser'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'httplib')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chrisp/github/s3-tests/s3tests_boto3/fuzz/test/test_fuzzer.py", line 21, in <module>
    from ..headers import *
  File "/home/chrisp/github/s3-tests/s3tests_boto3/fuzz/headers.py", line 4, in <module>
    from httplib import BadStatusLine
ModuleNotFoundError: No module named 'httplib'

======================================================================
ERROR: Failure: SyntaxError (Missing parentheses in call to 'print'. Did you mean print('original  hash: ', self.original_hash)? (realistic.py, line 50))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/chrisp/github/s3-tests/virtualenv/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/chrisp/github/s3-tests/virtualenv/lib64/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chrisp/github/s3-tests/s3tests_boto3/tests/test_realistic.py", line 1, in <module>
    from s3tests import realistic
  File "/home/chrisp/github/s3-tests/s3tests/realistic.py", line 50
    print 'original  hash: ', self.original_hash
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('original  hash: ', self.original_hash)?

----------------------------------------------------------------------
Ran 5 tests in 0.376s

FAILED (errors=6)
```

**Comment by gaul** [comment]
I encounter the same issues.  Does master work today or does it need #264 or other fixes?

**Comment by cbodley** [comment]
s3-tests doesnt support python3 yet. if your distro defaults to python3, you can force 2.7 in bootstrap with something like:
```diff
diff --git a/bootstrap b/bootstrap
index d7e66dc..23d25e0 100755
--- a/bootstrap
+++ b/bootstrap
@@ -34,7 +34,7 @@ elif [ -f /etc/redhat-release ]; then
     fi
 fi
 
-virtualenv --no-site-packages --distribute virtualenv
+virtualenv -p python2.7 --no-site-packages --distribute virtualenv
 
 # avoid pip bugs
 ./virtualenv/bin/pip install --upgrade pip
```

**Comment by linnemannr** [comment]
Python 2 is EOLed on Jan 1, is there any current effort to transition to Python 3?
