### ISSUE TITLE
In teuthology , test_bucket_list_return_data_versioning is failed?

### ISSUE THREAD

**Issue by Dreamyu20xx** [ceph/s3-tests#423]
Hi, cepher:
when test s3tests_boto3.functional.test_s3.test_bucket_list_return_data_versioning case ,It reported an error.
The result:

> 2021-12-29T18:15:55.326 INFO:teuthology.orchestra.run.anna001.stderr:======================================================================
2021-12-29T18:15:55.326 INFO:teuthology.orchestra.run.anna001.stderr:ERROR: s3tests_boto3.functional.test_s3.test_bucket_list_return_data_versioning
2021-12-29T18:15:55.326 INFO:teuthology.orchestra.run.anna001.stderr:----------------------------------------------------------------------
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:Traceback (most recent call last):
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:    self.test(*self.arg)
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/s3tests_boto3/functional/test_s3.py", line 1739, in test_bucket_list_return_data_versioning
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:    response  = client.list_object_versions(Bucket=bucket_name)
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/client.py", line 391, in _api_call
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:    return self._make_api_call(operation_name, kwargs)
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/client.py", line 713, in _make_api_call
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:    model=operation_model, context=request_context
2021-12-29T18:15:55.327 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/hooks.py", line 357, in emit
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:    return self._emitter.emit(aliased_event_name, **kwargs)
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:    return self._emit(event_name, kwargs)
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:    response = handler(**kwargs)
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/handlers.py", line 767, in decode_list_object_versions
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:    context=context
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:  File "/mnt/cephtest/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/handlers.py", line 776, in _decode_list_object
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:    parsed[key] = unquote_str(parsed[key])
2021-12-29T18:15:55.328 INFO:teuthology.orchestra.run.anna001.stderr:  File "/usr/lib64/python3.6/urllib/parse.py", line 751, in unquote_plus
2021-12-29T18:15:55.329 INFO:teuthology.orchestra.run.anna001.stderr:    string = string.replace('+', ' ')
2021-12-29T18:15:55.329 INFO:teuthology.orchestra.run.anna001.stderr:AttributeError: 'list' object has no attribute 'replace'
>
**packeages:**
PyYAML-6.0 boto-2.49.0 boto3-1.20.26 botocore-1.23.26 certifi-2021.10.8 charset-normalizer-2.0.9 gevent-21.12.0 greenlet-1.1.2 httplib2-0.20.2 idna-3.3 isodate-0.6.1 jmespath-0.10.0 lxml-4.7.1 munch-2.5.0 nose-1.3.7 pyparsing-3.0.6 python-dateutil-2.8.2 pytz-2021.3 requests-2.26.0 s3transfer-0.5.0 six-1.16.0 urllib3-1.26.7 zope.event-4.5.0 zope.interface-5.4.0
Have you encountered the same problem again? Can anyone help me?

**Comment by Dreamyu20xx** [comment]
Current list_object_versions(Bucket=bucket_name,  EncodingType='url')  is ok. I feel there is a problem with botocore. because In botocore=1.12.0 it is fine.
