### ISSUE TITLE
Tests using _create_key_with_random_content give HTTP error 413 "Request Entity Too Large"

### ISSUE THREAD

**Issue by ZhuTopher** [ceph/s3-tests#436]
I've been consistently reproducing a `Request Entity Too Large` error in any tests that involve the `_create_key_with_random_content` helper function.
https://github.com/ceph/s3-tests/blob/76beb672d14b268737a1026c6fbdcafd57e91b8f/s3tests_boto3/functional/test_s3.py#L6802-L6813
- https://github.com/ceph/s3-tests/blob/76beb672d14b268737a1026c6fbdcafd57e91b8f/s3tests_boto3/functional/utils.py#L23-L40

An example stacktrace:
```
Running nosetest on s3tests_boto3.functional.test_get_obj_tagging
s3tests_boto3.functional.test_s3.test_get_obj_tagging ... ERROR

======================================================================
ERROR: s3tests_boto3.functional.test_s3.test_get_obj_tagging
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/cephs3tests/s3-tests-master/virtualenv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/cephs3tests/s3-tests-master/s3tests_boto3/functional/test_s3.py", line 11760, in test_get_obj_tagging
    bucket_name = _create_key_with_random_content(key)
  File "/opt/cephs3tests/s3-tests-master/s3tests_boto3/functional/test_s3.py", line 6811, in _create_key_with_random_content
    client.put_object(Bucket=bucket_name, Key=keyname, Body=data)
  File "/opt/cephs3tests/s3-tests-master/virtualenv/lib/python3.6/site-packages/botocore/client.py", line 401, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/cephs3tests/s3-tests-master/virtualenv/lib/python3.6/site-packages/botocore/client.py", line 731, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (413) when calling the PutObject operation: Request Entity Too Large
```

S3 has a 5GB body limit on `PutObject` requests. [Doc link](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html):
> Upload an object in a single operation using the AWS SDKs, REST API, or AWS CLI—With a single PUT operation, you can upload a single object up to 5 GB in size.

When I print the length of the generated data I don't see it exceeding the 5 GB limit, so why is this request failing?

**Comment by ZhuTopher** [comment]
My mistake, I was making requests through an Nginx reverse proxy and was hitting the size limits there.
