### ISSUE TITLE
Check grants on test_object_header_acl_grants failing due sort problem

### ISSUE THREAD

**Issue by monary** [ceph/s3-tests#68]
test_object_header_acl_grants is failing with 
Traceback (most recent call last):
  File "/tmp/s3-tests-master/virtualenv/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/s3-tests-master/s3tests/functional/test_s3.py", line 3861, in test_object_header_acl_grants
    type='CanonicalUser',
  File "/tmp/s3-tests-master/s3tests/functional/test_s3.py", line 80, in check_grants
    eq(g.permission, w.pop('permission'))
AssertionError: u'FULL_CONTROL' != 'READ'

And it seems is due sorting that is failing. I changed to sort by permission in check_grants and the compares succeed.

def check_grants(got, want):
...
    eq(len(got), len(want))
    got = sorted(got, key=operator.attrgetter('permission'))
    want = sorted(want, key=operator.itemgetter('permission'))
...

**Comment by andrewgaul** [comment]
@monary Sorry I do not follow -- why would this test sort on permission instead of the unique ID?  Can you dump the actual `got` and `wanted` inputs?
