### ISSUE TITLE
Etags different due double quotes in test_bucket_list_return_data

### ISSUE THREAD

**Issue by monary** [ceph/s3-tests#69]
Traceback (most recent call last):
Etags different due double quotes in test_bucket_list_return_data
 
 File "/tmp/s3-tests-master/virtualenv/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/s3-tests-master/s3tests/functional/test_s3.py", line 719, in test_bucket_list_return_data
    eq(key.etag, key_data['etag'])
AssertionError: u'37b51d194a7513e45b56f6524f2d51f2' != '"37b51d194a7513e45b56f6524f2d51f2"'

Suggestion:
etag': key.etag.strip('"'),
Line 705 on s3-tests-master/s3tests/functional/test_s3.py

**Comment by andrewgaul** [comment]
@monary Which S3 implementation are you testing against?  Perhaps it is missing a quote somewhere since this test works correctly with AWS and S3Proxy?
